### ISSUE TITLE
Error when trying to place blocks with easyplacemode from litematica

### ISSUE THREAD

**Issue by boasbakker** [gnembon/carpet-extra#207]
When I try to place sertain blocks with the "facing" blocktag, with easyplacemode from litematica, it isnt placed in the correct orientation, it creates a weird ghostblock state, and it gives the error given below. The server doesnt crash or something, the block just doesnt place. What I mean with "a weird ghostblock state", is this: The schematica overlay sais the block still needs to be placed, it sais it is a missing block, while when turning the overlay rendering off, the block is there, with the correct orientation, and you can walk on it. However, the block you are walking on is a ghostblock, and when right clicking it, it disapears. 

[21:24:29] [Server thread/FATAL]: Error executing task on Server
java.lang.IllegalArgumentException: Cannot set property class_2753{name=facing, clazz=class net.minecraft.class_2350, values=[north, south, west, east]} to up on Block{minecraft:dark_oak_trapdoor}, it is not an allowed value
        at net.minecraft.class_2688.method_11657(class_2688.java:125) ~[intermediary-server.jar:?]
        at carpetextra.utils.BlockPlacer.alternativeBlockPlacement(BlockPlacer.java:75) ~[carpet-extra.jar:?]
        at net.minecraft.class_1747.redirect$zfg000$getAlternatePlacement(class_1747.java:524) ~[intermediary-server.jar:?]
        at net.minecraft.class_1747.method_7707(class_1747.java:117) ~[intermediary-server.jar:?]
        at net.minecraft.class_1747.method_7712(class_1747.java:69) ~[intermediary-server.jar:?]
        at net.minecraft.class_1747.method_7884(class_1747.java:49) ~[intermediary-server.jar:?]
        at net.minecraft.class_1799.method_7981(class_1799.java:244) ~[intermediary-server.jar:?]
        at net.minecraft.class_3225.method_14262(class_3225.java:347) ~[intermediary-server.jar:?]
        at net.minecraft.class_3244.method_12046(class_3244.java:1051) ~[intermediary-server.jar:?]
        at net.minecraft.class_2885.method_12547(class_2885.java:36) ~[intermediary-server.jar:?]
        at net.minecraft.class_2885.method_11054(class_2885.java:10) ~[intermediary-server.jar:?]
        at net.minecraft.class_2600.method_11072(class_2600.java:21) ~[intermediary-server.jar:?]
        at net.minecraft.class_3738.run(class_3738.java:18) ~[intermediary-server.jar:?]
        at net.minecraft.class_1255.method_18859(class_1255.java:144) ~[intermediary-server.jar:?]
        at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:763) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:159) ~[intermediary-server.jar:?]
        at net.minecraft.class_1255.method_16075(class_1255.java:118) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:745) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:739) ~[intermediary-server.jar:?]
        at net.minecraft.class_1255.method_18857(class_1255.java:127) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:724) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.handler$zjh000$modifiedRunLoop(MinecraftServer.java:4820) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:653) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:259) ~[intermediary-server.jar:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_281]

**Comment by boasbakker** [comment]
Btw, the only block I have tested this for is dark_oak_trapdoor, the weird thing is that spruce_trapdoor works fine.
dark_oak_trapdoor always has the problem (maybe only when the orientation is different then what it would be without accurateblockplacement?)
dark_oak_stairs sometimes has the problem (maybe only when the orientation is different then what it would be without accurateblockplacement?)
spruce_trapdoor never has the problem
