### ISSUE TITLE
Bypass UpdateSuppressionCrashFix using Soulbound Chests

### ISSUE THREAD

**Issue by fxmorin** [gnembon/carpet-extra#208]
As shown here: https://www.youtube.com/watch?v=RchVIanvMVg
Getting Soulbound to a chest then leaving the server will crash the game

```
Description: Exception in server tick loop

carpetextra.helpers.ThrowableSuppression: Update suppression
	at net.minecraft.world.World.handler$zkp000$checkUpdateSuppression(World.java:3635)
	at net.minecraft.world.World.updateNeighbor(World.java:304)
	at net.minecraft.world.World.updateNeighborsAlways(World.java:266)
	at net.minecraft.block.entity.ChestBlockEntity.onInvOpenOrClose(ChestBlockEntity.java:201)
	at net.minecraft.block.entity.ChestBlockEntity.onClose(ChestBlockEntity.java:192)
	at net.minecraft.screen.GenericContainerScreenHandler.close(GenericContainerScreenHandler.java:110)
	at net.minecraft.entity.player.PlayerEntity.remove(PlayerEntity.java:1237)
	at net.minecraft.server.world.ServerWorld.removePlayer(ServerWorld.java:1004)
	at net.minecraft.server.PlayerManager.remove(PlayerManager.java:368)
	at net.minecraft.server.network.ServerPlayNetworkHandler.onDisconnected(ServerPlayNetworkHandler.java:1037)
	at net.minecraft.network.ClientConnection.handleDisconnection(ClientConnection.java:360)
	at net.minecraft.server.ServerNetworkIo.tick(ServerNetworkIo.java:165)
	at net.minecraft.server.MinecraftServer.tickWorlds(MinecraftServer.java:878)
	at net.minecraft.server.dedicated.MinecraftDedicatedServer.tickWorlds(MinecraftDedicatedServer.java:285)
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:804)
	at net.minecraft.server.MinecraftServer.handler$zbo000$modifiedRunLoop(MinecraftServer.java:2449)
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:646)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:227)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by fxmorin** [comment]
@whoImT

**Comment by altrisi** [comment]
Closing this because I'd assume you checked this when porting it to fabric carpet, if not it's not relevant anyway given it's no longer in carpet extra and because update suppression via exceptions isn't really a thing anymore.
